[package]
name = "two_notes"
version = "0.2.0"
description = "Personal quick capture notes"
authors = ["2notes"]
edition = "2021"

[lib]
name = "two_notes_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
thiserror = "2.0.18"
log = "0.4.33"
uuid = { version = "1.23.4", features = ["v4", "serde"] }
time = { version = "0.3.51", features = ["formatting", "parsing", "serde"] }
sanitize-filename = "0.6.0"
tempfile = "3.27.0"
tauri-plugin-global-shortcut = "2.3.2"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-log = "2.8.0"
tauri-plugin-dialog = "2.7.1"
tauri-plugin-window-state = "2.4.1"
tauri-plugin-single-instance = "2.4.2"
serde_yml = "0.0.13"
ts-rs = { version = "12.0.1", features = ["uuid"] }
